apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: tripinsightsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryzlt8225.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        env:
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                key: SQL_SERVER
                name: mydrivingdb-secret
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                key: SQL_DBNAME
                name: mydrivingdb-secret
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                key: SQL_USER
                name: mydrivingdb-secret
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: SQL_PASSWORD
                name: mydrivingdb-secret
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  labels:
    run: trips
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: trips
