apiVersion: v1
kind: Service
metadata:
  name: poi-service
  labels:
    app: poi
    tier: api
  namespace: tripinsightsapi
spec:
  type: ClusterIP
  selector:
    app: poi
    tier: api  
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
