apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2021-12-01T00:16:17Z"
  generation: 2
  labels:
    app: poi
  name: tripviewer-deployment
  namespace: tripinsightsapi
  resourceVersion: "6354"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: poi
      tier: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: poi
        tier: api
    spec:
      containers:
      - env:
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              key: SQL_SERVER
              name: mydrivingdb-secret
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              key: SQL_DBNAME
              name: mydrivingdb-secret
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              key: SQL_USER
              name: mydrivingdb-secret
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SQL_PASSWORD
              name: mydrivingdb-secret
        image: registryzlt8225.azurecr.io/tripinsights/tripviewer:1.0
        imagePullPolicy: IfNotPresent
        name: poi
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-12-01T00:16:30Z"
    lastUpdateTime: "2021-12-01T00:16:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-12-01T00:16:17Z"
    lastUpdateTime: "2021-12-01T00:26:41Z"
    message: ReplicaSet "poi-deployment-7d6755b7bf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
