apiVersion: v1
kind: Service
metadata:
  labels:
    app: tripviewer
  name: tripviewer-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tripviewer
  sessionAffinity: None
  type: LoadBalancer
